AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AJJK_Planner.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Index.cshtml.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using AJJK_CL;
using System.Data;
#nullable disable

namespace AJJK_Planner.Pages
{
    [BindProperties]
    public class IndexModel : PageModel
    {
        public int AJJK_EDIT_ID { get; set; }
        public int AJJK_EDIT_ID2 { get; set; }
        public string AJJK_Id { get; set; }
        public string AJJK_Name { get; set; }
        public string AJJK_Subject { get; set; }
        public string AJJK_Date { get; set; }
        public string AJJK_Description { get; set; }
        public string AJJK_Status { get; set; }
        public string AJJK_Id2 { get; set; }
        public string AJJK_Name2 { get; set; }
        public string AJJK_Subject2 { get; set; }
        public string AJJK_Date2 { get; set; }
        public string AJJK_Description2 { get; set; }
        public string AJJK_Status2 { get; set; }
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _AJJK_Config;
        public IEnumerable<AJJK_Class> List { get; set; }
        public IndexModel(ILogger<IndexModel> logger,IConfiguration AJJK_config)
        {
            _logger = logger;
            _AJJK_Config = AJJK_config;

            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            List = AJJK_a.Query<AJJK_Class>("[AJJK_dis]", commandType:CommandType.StoredProcedure);

        }
        public IActionResult OnPostAJJK_sea()
        {
            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            List = AJJK_a.Query<AJJK_Class>("[AJJK_sea]",new{
                @AJJK_Name=$"%{AJJK_Name2}%"
            }, commandType: CommandType.StoredProcedure);
            return Page();
        }
        public IActionResult OnPostAJJK_edi()
        {
            AJJK_EDIT_ID = AJJK_EDIT_ID2;
            AJJK_Id = AJJK_Id2;
            AJJK_Name =AJJK_Name2;
            AJJK_Subject=AJJK_Subject2;
            AJJK_Date=AJJK_Date2;
            AJJK_Description=AJJK_Description2;
            AJJK_Status=AJJK_Status2;
            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            List = AJJK_a.Query<AJJK_Class>("[AJJK_dis]", commandType: CommandType.StoredProcedure);
            return Page();
        }
        public IActionResult OnPostAJJK_add()
        {
            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            AJJK_a.Query("[AJJK_add]",new{
            @AJJK_Id=AJJK_Id,
            @AJJK_Name=AJJK_Name,
            @AJJK_Subject=AJJK_Subject,
            @AJJK_Date=AJJK_Date,
            @AJJK_Description=AJJK_Description,
            @AJJK_Status= AJJK_Status
            }, commandType: CommandType.StoredProcedure);
            return RedirectToPage();
        }
        public IActionResult OnPostAJJK_del()
        {
            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            AJJK_a.Query("[AJJK_del]",new{
                @AJJK_Id = AJJK_Id2
            }, commandType: CommandType.StoredProcedure);
            return RedirectToPage();
        }
        public IActionResult OnPostAJJK_upd()
        {
            var AJJK_a = new SqlConnection(_AJJK_Config.GetConnectionString("AJJK_DB"));
            AJJK_a.Query("[AJJK_upd]",new {
                @AJJK_EDIT_ID = AJJK_EDIT_ID,
            @AJJK_Id = AJJK_Id,
            @AJJK_Name = AJJK_Name,
            @AJJK_Subject = AJJK_Subject,
            @AJJK_Date = AJJK_Date,
            @AJJK_Description = AJJK_Description,
            @AJJK_Status = AJJK_Status
            }, commandType: CommandType.StoredProcedure);
            return RedirectToPage();
        }


    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AJJK_Planner.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/Create.cshtml.cs
using AJJK_CL;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Data;
#nullable disable

namespace AJJK_Planner.Pages
{
    public class CreateModel : PageModel
    {
        private readonly IConfiguration _config;

        [BindProperty]
        public Accounts createacc { get; set; }

        public CreateModel(IConfiguration config)
        {
            _config = config;
        }

        public IActionResult OnPostCreate()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using var sqlcon = new SqlConnection(_config.GetConnectionString("AJJK_DB"));
            var storeProcedure = "[dbo].[Create]";
            var parameter = new DynamicParameters();
            parameter.Add("@username", createacc.username, DbType.String, ParameterDirection.Input);
            parameter.Add("@password", createacc.password, DbType.String, ParameterDirection.Input);
            sqlcon.Execute(storeProcedure, parameter, commandType: CommandType.StoredProcedure);
            return RedirectToPage("/Login");
        }
    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/Login.cshtml.cs
using AJJK_CL;
using Dapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Data;
using System.Security.Claims;
#nullable disable

namespace AJJK_Planner.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IConfiguration config;

        [BindProperty]
        public Accounts acc { get; set; }
        public bool IsAuthenticated { get; private set; }
        public LoginModel(IConfiguration _config)
        {
            config = _config;
        }
        public IActionResult OnGet()
        {
            IsAuthenticated = User?.Identity?.IsAuthenticated ?? false;
            return Page();
        }
        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                using var sqlcon = new SqlConnection(config.GetConnectionString("AJJK_DB"));
                var storeProcedure = "[dbo].[Login]";
                var parameter = new DynamicParameters();
                parameter.Add("@username", acc.username, DbType.String, ParameterDirection.Input);
                parameter.Add("@password", acc.password, DbType.String, ParameterDirection.Input);
                var user = sqlcon.QueryFirstOrDefault<Accounts>(storeProcedure, parameter);
                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, user.username),
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties { };

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                    return RedirectToPage("/AJJK_Index");
                }
            }

            return Page();
        }
    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/Shared/LoginLayout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AJJK_Planner.Pages.Shared
{
    public class LoginLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Error.cshtml
@page
@model ErrorModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to the <strong>Development</strong> environment displays detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<link rel="stylesheet" href="~/css/Indexcss.css" />
<form method="post" asp-page-handler="AJJK_sea">
    <input name="AJJK_Name2" />
    <button type="submit">SEARCH</button>
</form>
<table class="table">
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>SUBJECT</th>
        <th>DATE</th>
        <th>DESCRIPTION</th>
        <th>STATUS</th>
    </tr>
    @foreach (var AJJK in Model.List)
    {
        <tr>
            <td>@AJJK.AJJK_Id</td>
            <td>@AJJK.AJJK_Name</td>
            <td>@AJJK.AJJK_Subject</td>
            <td>@AJJK.AJJK_Date</td>
            <td>@AJJK.AJJK_Description</td>
            <td>@AJJK.AJJK_Status</td>
            <td>
                <form method="post" asp-page-handler="AJJK_del">
                    <input name="AJJK_EDIT_ID2" value="@AJJK.AJJK_EDIT_ID" hidden />
                    <input name="AJJK_Id2" value="@AJJK.AJJK_Id" hidden />
                    <input name="AJJK_Name2" value="@AJJK.AJJK_Name" hidden />
                    <input name="AJJK_Subject2" value="@AJJK.AJJK_Subject" hidden />
                    <input name="AJJK_Date2" value="@AJJK.AJJK_Date" hidden />
                    <input name="AJJK_Description2" value="@AJJK.AJJK_Description" hidden />
                    <input name="AJJK_Status2" value="@AJJK.AJJK_Status" hidden />
                    <button type="submit" method="post" asp-page-handler="AJJK_edi">EDIT</button>
                    <button type="submit">DELETE</button>
                </form>
            </td>
        </tr>
    }
</table>
<form method="post" asp-page-handler="AJJK_add">
    <input name="AJJK_EDIT_ID" value="@Model.AJJK_EDIT_ID" hidden /><br />
    <input name="AJJK_Id" value="@Model.AJJK_Id" placeholder="ID" /><br />
    <input name="AJJK_Name" value="@Model.AJJK_Name" placeholder="NAME" /><br />
    <input name="AJJK_Subject" value="@Model.AJJK_Subject" placeholder="SUBJECT" /><br />
    <input name="AJJK_Date" value="@Model.AJJK_Date" placeholder="DATE" type="date" /><br />
    <input name="AJJK_Description" value="@Model.AJJK_Description" placeholder="DESCRIPTION" /><br />
    <div class="radio-container">
        <input type="radio" id="finished" name="AJJK_Status" value="Finished" />
        <label for="finished">Finished</label>
    </div>
    <div class="radio-container">
        <input type="radio" id="ongoing" name="AJJK_Status" value="OnGoing" />
        <label for="ongoing">OnGoing</label>
    </div>
    <div class="radio-container">
        <input type="radio" id="unfinished" name="AJJK_Status" value="Unfinished" />
        <label for="unfinished">Unfinished</label>
    </div>
    <button type="submit">CREATE</button>
    <button type="submit" method="post" asp-page-handler="AJJK_upd">UPDATE</button>
</form>

AJJK_StudentPlanner/AJJK_Planner/Pages/AJJK_Privacy.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

AJJK_StudentPlanner/AJJK_Planner/Pages/Create.cshtml
@page
@model AJJK_Planner.Pages.CreateModel
@{
    Layout = "LoginLayout";
}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- <title>Neumorphism Login Form UI | CodingNepal</title> -->
    <link rel="stylesheet" href="/css/Login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
    <div class="content">
        <div class="text">
            Create Account Form
        </div>
        <form method="post" asp-page-handler="Create">
            <div class="field">
                <input asp-for="createacc.username" type="text" required>
                <span class="fas fa-user"></span>
                <label>Email or Phone</label>
            </div>
            <div class="field">
                <input asp-for="createacc.password" type="password" required>
                <span class="fas fa-lock"></span>
                <label>Password</label>
            </div>
            <button>Sign up</button>
            <div class="sign-up">
                have an account?
                <a href="/Login">Login</a>
            </div>
        </form>
    </div>
</body>
</html>

AJJK_StudentPlanner/AJJK_Planner/Pages/Login.cshtml
@page
@model AJJK_Planner.Pages.LoginModel
@{
    Layout = "LoginLayout";
}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- <title>Neumorphism Login Form UI | CodingNepal</title> -->
    <link rel="stylesheet" href="/css/Login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
    <div class="content">
        <div class="text">
            Login Form
        </div>
        <form method="post" asp-page-handler="Login">
            <div class="field">
                <input asp-for="acc.username" type="text" required>
                <span class="fas fa-user"></span>
                <label>Email or Phone</label>
            </div>
            <div class="field">
                <input asp-for="acc.password" type="password" required>
                <span class="fas fa-lock"></span>
                <label>Password</label>
            </div>
            <div class="forgot-pass">
                <a href="#">Forgot Password?</a>
            </div>
            <button>Sign in</button>
            <div class="sign-up">
                Not a member?
                <a href="/Create">signup now</a>
            </div>
        </form>
    </div>
</body>
</html>