DausanBigStore/DausanBigStore/Pages/CreateAccount.cshtml.cs
using Dapper;
using DausanCoreLib.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Data;
#nullable disable

namespace DausanBigStore.Pages
{
    public class CreateAccountModel : PageModel
    {
        private readonly IConfiguration config;


        [BindProperty]
        public Accounts createacc { get; set; }
       
        public CreateAccountModel(IConfiguration CONFIG)
        {
            config= CONFIG;
        }
        public IActionResult OnPostCreate()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using var sqlcon = new SqlConnection(config.GetConnectionString("DUA"));
            var storeProcedure = "[dbo].[Create]";
            var parameter = new DynamicParameters();
            parameter.Add("@username", createacc.username, DbType.String, ParameterDirection.Input);
            parameter.Add("@password", createacc.password, DbType.String, ParameterDirection.Input);
            sqlcon.Execute(storeProcedure, parameter, commandType: CommandType.StoredProcedure);
            return RedirectToPage("/Index");
        }
    }
}

DausanBigStore/DausanBigStore/Pages/Dashboard.cshtml.cs
#nullable disable

using Dapper;
using DausanCoreLib.Models;
using DausanCoreLib.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;


namespace DausanBigStore.Pages
{
    public class DashboardModel : PageModel
    {
        private readonly ILogger<DashboardModel> _logger;
        private readonly IStore _store;
        private IBigStoreModel _product;
        private readonly IConfiguration _config;

        public string Title { get; set; }

        [BindProperty]
        public BigStoreModel Product { get; set; }

        [BindProperty]
        public SearchModel Search { get; set; }
        public IEnumerable<IBigStoreModel> ProductList; //=> _store.ProductList;

        public DashboardModel(ILogger<DashboardModel> logger, IStore store, IBigStoreModel product, IConfiguration config)
        {
            Title = "Welcome! " + DateTime.Now.ToString();
            _logger = logger;
            _store = store;
            _product = product;
            _config = config;
            var d = new SqlConnection(_config.GetConnectionString("DUA"));
            ProductList = d.Query<BigStoreModel>("displayProduct");
        }
        public IActionResult OnGet()
        {
            Title = string.Empty;
            Product = new();
            return Page();
        }
        public IActionResult OnPostAddProduct()
        {
            if (ModelState.IsValid)
            {
                var d = new SqlConnection(_config.GetConnectionString("DUA"));
                var sqlString = "createProduct";
                var parameters = new DynamicParameters();
                parameters.Add("@ProductCode", Product.ProductCode, DbType.String, ParameterDirection.Input);
                parameters.Add("@ProductName", Product.ProductName, DbType.String, ParameterDirection.Input);
                parameters.Add("@ProductPrice", Product.ProductPrice, DbType.String, ParameterDirection.Input);

                d.Execute(sqlString, parameters);

                ProductList = d.Query<BigStoreModel>("displayProduct");
            }
            return Page();
        }

        public IActionResult OnGetEditProduct(string code)
        {

            if (string.IsNullOrEmpty(code))
            {
                Title = string.Empty;
                Product = new();
            }
            else
            {
                using var d = new SqlConnection(_config.GetConnectionString("DUA"));
                var sqlString = "findProductById";
                var parameters = new DynamicParameters();
                parameters.Add("@ProductCode", code, DbType.String, ParameterDirection.Input);
                var result = d.Query<BigStoreModel>(sqlString, parameters);
                Product = result.FirstOrDefault();
            }
            return Page();
        }
        public IActionResult OnGetDeleteProduct(string code)
        {


            Product = new();

            if (string.IsNullOrEmpty(code))
            {
            }
            else
            {
                //_store.DeleteStudent(id
                using var d = new SqlConnection(_config.GetConnectionString("DUA"));
                var sqlString = "delete";
                var parameters = new DynamicParameters();
                parameters.Add("@ProductCode", code, DbType.String, ParameterDirection.Input);

                d.Execute(sqlString, parameters);

                ProductList = d.Query<BigStoreModel>("displayProduct");
            }

            return RedirectToPage();
        }
        public IActionResult OnPostUpdate()
        {
            if (ModelState.IsValid)
            {
                var d = new SqlConnection(_config.GetConnectionString("DUA"));
                var sqlString = "update";
                var parameters = new DynamicParameters();
                parameters.Add("@ProductCode", Product.ProductCode, DbType.String, ParameterDirection.Input);
                parameters.Add("@ProductName", Product.ProductName, DbType.String, ParameterDirection.Input);
                parameters.Add("@ProductPrice", Product.ProductPrice, DbType.String, ParameterDirection.Input);

                d.Execute(sqlString, parameters);

                ProductList = d.Query<BigStoreModel>("displayProduct");

            }
            return RedirectToPage();
        }
        public IActionResult OnPostSearchBigStore()
        {
            if (ModelState.IsValid)
            {
                _store.FindBigStoreByKeyword(Search.Keyword);
            }
            return RedirectToPage();
        }
        public IActionResult OnPostDisplayBigStore()
        {
            if (ModelState.IsValid)
            {
                Title = $"{Product.ProductName}  -  {Product.ProductCode}";

                _store.DisplayBigStore(Product);
            }
            return RedirectToPage();
        }


    }
}

DausanBigStore/DausanBigStore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DausanBigStore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DausanBigStore/DausanBigStore/Pages/Index.cshtml.cs
#nullable disable
using System.Security.Claims;
using Dapper;
using DausanCoreLib.Models;
using DausanCoreLib.Stores;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;


namespace DausanBigStore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _config;

        [BindProperty]
        public Accounts acc { get; set; }
        public bool IsAuthenticated { get; private set; }
        public IndexModel(ILogger<IndexModel> logger, IConfiguration config)
        {
           _config= config;
            _logger = logger;
          
        }
        public IActionResult OnGet()
        {
            IsAuthenticated = User?.Identity?.IsAuthenticated ?? false;
            return Page();
        }
        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                using var sqlcon = new SqlConnection(_config.GetConnectionString("DUA"));
                var storeProcedure = "[dbo].[Login]";
                var parameter = new DynamicParameters();
                parameter.Add("@username", acc.username, DbType.String, ParameterDirection.Input);
                parameter.Add("@password", acc.password, DbType.String, ParameterDirection.Input);
               var user = sqlcon.QueryFirstOrDefault<Accounts>(storeProcedure, parameter);
                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, user.username),
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties { };

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                    return RedirectToPage("/Dashboard");
                }
            }

            return Page();
        }
    }
}

DausanBigStore/DausanBigStore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DausanBigStore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DausanBigStore/DausanBigStore/Pages/CreateAccount.cshtml
@page
@model DausanBigStore.Pages.CreateAccountModel
@{
    Layout = "Sign In";
    ViewData["Title"] = "Login Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTML5 Login Form with validation Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="/css/Login.css">

</head>
<body>
    <!-- partial:index.partial.html -->
    <div id="login-form-wrap">
        <h2>Sign Up</h2>
        <form id="login-form" method="post">
            <p>
                <input asp-for="createacc.username" type="text"  placeholder="Username" required><i class="validation"><span></span><span></span></i>
            </p>
            <p>
                <input asp-for="createacc.password" type="password" placeholder="Password" required><i class="validation"><span></span><span></span></i>
            </p>
            <button asp-page-handler="Create">Create</button>
        </form>
        <div id="create-account-wrap">
            <p>have a account? <a href="/Index">Login</a><p>
        </div><!--create-account-wrap-->
    </div><!--login-form-wrap-->
    <!-- partial -->

</body>
</html>

DausanBigStore/DausanBigStore/Pages/Dashboard.cshtml
@page
@model DausanBigStore.Pages.DashboardModel
@{
}

<div class="product-List">
    <h3>
        Product Detail

    </h3>
</div>


<form style="margin-bottom:20px;" method="post" asp-page-handler="AddProduct">
    <div class="form-group">
        <label for="Product.ProductCode">Code: </label>
        <input asp-for="Product.ProductCode"
               class="form-control" />
    </div>
    <div class="form-group">
        <label for="Product.ProductName">Name: </label>
        <input asp-for="Product.ProductName"
               class="form-control" />
    </div>
    <div class="form-group">
        <label for="Product.ProductPrice">Price: </label>
        <input asp-for="Product.ProductPrice"
               class="form-control" />
    </div>

    <button asp-page-handler="Update" class="btn btn-primary" type="submit">Update</button>    
    <button  class="btn btn-primary" type="submit">Create</button>
</form>


<div class="product-List">
   
    <form asp-page-handler="DisplayBigStore">
        <label> Product List</label>
        <button class="btn btn-primary">New</button>

    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model.ProductList)
            {
                <tr>
                    <td>@item.ProductCode</td>
                    <td>@item.ProductName</td>
                    <td>@item.ProductPrice</td>
                    <td>
                        <span><a role="button"  asp-route-code="@item.ProductCode" asp-page-handler="EditProduct">Edit</a></span>
                        <span><a role="button"  asp-route-code="@item.ProductCode" asp-page-handler="DeleteProduct">Delete</a></span>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<form id="student-search-form" method="post" asp-page-handler="SearchBigStore">
    <label for="Search.Keyword">Keyword</label>
    <input asp-for="Search.Keyword" class="form-control" />

    <button class="btn btn-primary" type="submit">Search</button>
</form>

<style>
    body {
        background-color: cadetblue;
    }
</style>

 

DausanBigStore/DausanBigStore/Pages/Index.cshtml
@page
@model IndexModel
@{

    Layout = "Sign In";
    ViewData["Title"] = "Login Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTML5 Login Form with validation Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="/css/Login.css">

</head>
<body>
    <!-- partial:index.partial.html -->
    <div id="login-form-wrap">
        <h2>Login</h2>
        <form id="login-form" method="post">
            <p>
                <input asp-for="acc.username" type="text" id="username" name="username" placeholder="Username" required><i class="validation"><span></span><span></span></i>
            </p>
            <p>
                <input asp-for="acc.password" type="password" id="password" name="password" placeholder="Password" required><i class="validation"><span></span><span></span></i>
            </p>
            <button asp-page-handler="Login">Login</button>
        </form>
        <div id="create-account-wrap">
            <p>Not a member? <a href="/CreateAccount">Create Account</a><p>
        </div><!--create-account-wrap-->
    </div><!--login-form-wrap-->
    <!-- partial -->

</body>
</html>