SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Create.cshtml.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using SongcayawoninalIPT102ProjectFinal.Classes;
using System.Data;
#nullable disable

namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class CreateModel : PageModel
    {
        private readonly IConfiguration _config;

        [BindProperty]
        public Accounts createacc { get; set; }

        public CreateModel(IConfiguration config)
        {
            _config = config;
        }

        public IActionResult OnPostCreate()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using var sqlcon = new SqlConnection(_config.GetConnectionString("SW"));
            var storeProcedure = "[dbo].[Create]";
            var parameter = new DynamicParameters();
            parameter.Add("@username", createacc.username, DbType.String, ParameterDirection.Input);
            parameter.Add("@password", createacc.password, DbType.String, ParameterDirection.Input);
            sqlcon.Execute(storeProcedure, parameter, commandType: CommandType.StoredProcedure);
            return RedirectToPage("/Index");
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/CreatePlayer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SongcayawoninalIPT102ProjectFinal.Classes;
#nullable disable
namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class CreatePlayerModel : PageModel
    {
        [BindProperty]
        public Players playerInput {  get; set; }

        private ConDb con;

        public CreatePlayerModel(ConDb _con)
        {
        con = _con;
        }
        public IActionResult OnPostCreate()
        {
            con.Create(playerInput);
            playerInput = new Players();    
            return Page();
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SongcayawoninalIPT102ProjectFinal.Classes;
using System.Data;
using System.Security.Claims;
using Dapper;
using Microsoft.Data.SqlClient;
#nullable disable
namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _config;

        [BindProperty]
        public Accounts acc { get; set; }
        public bool IsAuthenticated { get; private set; }
        public IndexModel(ILogger<IndexModel> logger, IConfiguration config)
        {
            _config = config;
            _logger = logger;

        }
        public IActionResult OnGet()
        {
            IsAuthenticated = User?.Identity?.IsAuthenticated ?? false;
            return Page();
        }
        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                using var sqlcon = new SqlConnection(_config.GetConnectionString("SW"));
                var storeProcedure = "[dbo].[Login]";
                var parameter = new DynamicParameters();
                parameter.Add("@username", acc.username, DbType.String, ParameterDirection.Input);
                parameter.Add("@password", acc.password, DbType.String, ParameterDirection.Input);
                var user = sqlcon.QueryFirstOrDefault<Accounts>(storeProcedure, parameter);
                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, user.username),
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties { };

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                    return RedirectToPage("/CreatePlayer");
                }
            }

            return Page();
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/PlayerDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SongcayawoninalIPT102ProjectFinal.Classes;
using System.Collections.Generic;

#nullable disable

namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class PlayerDetailsModel : PageModel
    {
        public IEnumerable<Players> playerOptions;
        public ConDb con;

        [BindProperty]
        public Players playD { get; set; }

        [BindProperty]
        public int PlayerDetailsId { get; set; }

        public PlayerDetailsModel(ConDb _con)
        {
            con = _con;
            playerOptions = con.playerlist();
            playD = new Players();
        }

        public IActionResult OnPostPlayerDetailsDisplay()
        {
            playD = con.PickedPlayer(PlayerDetailsId)?.FirstOrDefault();
            return Page();
        }

        public IActionResult OnPostPlayerDetailsDelete(int ID)
        {
            con.PlayerDetailsDelete(ID);
            playD = new Players();
            playerOptions = con.playerlist();
            return Page();
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/PlayerDetailsUpdate.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SongcayawoninalIPT102ProjectFinal.Classes;
using System.Numerics;
#nullable disable
namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class PlayerDetailsUpdateModel : PageModel
    {
        public IEnumerable<Players> playerOptions;
        public ConDb con;

        [BindProperty]
        public Players playUpdate { get; set; }

        [BindProperty]
        public int PlayerDetailsId { get; set; }
        public PlayerDetailsUpdateModel(ConDb _con)
        {
            con = _con;
            playerOptions = con.playerlist();
        }
        public IActionResult OnPostPlayerDetailsDisplay()
        {
            playUpdate = con.PickedPlayer(PlayerDetailsId)?.FirstOrDefault();
            return Page();
        }
        public IActionResult OnPostPlayerDetailsUpdate()
        {

            con.PlayerDetailsUpdate(playUpdate);
            playUpdate = new Players();
            playerOptions = con.playerlist();
            return Page();
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/SearchPlayer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using SongcayawoninalIPT102ProjectFinal.Classes;
using Dapper;
#nullable disable

namespace SongcayawoninalIPT102ProjectFinal.Pages
{
    public class SearchPlayerModel : PageModel
    {
        public List<Players> AllLogs { get; set; }
        private readonly IConfiguration config;
        private readonly SqlConnection connection;

        [BindProperty]
        public Players plays { get; set; }

        public SearchPlayerModel(IConfiguration _config)
        {
            config = _config;
            connection = new SqlConnection(config.GetConnectionString("SW"));
        }
        public void OnGet()
        {
        }
        public IActionResult OnPostSearch()
        {
            if (!string.IsNullOrEmpty(plays.PlayerName))
            {
                var sqlStr = "[dbo].[SearchByName]";
                var param = new { PlayerName = plays.PlayerName };
                AllLogs = connection.Query<Players>(sqlStr, param).ToList();
                return Page();
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Create.cshtml
@page
@model SongcayawoninalIPT102ProjectFinal.Pages.CreateModel
@{
    Layout = "LoginLayout";
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/Login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Create Form</title>
</head>
<body>

    <div class="container">
        <div class="title">
            <h2>Create</h2>
        </div>
        <form method="post">
            <div class="field">
                <i class="fa fa-envelope"></i>
                <input asp-for="createacc.username" type="email" placeholder="Email">
            </div>
            <div class="field">
                <i class="fa fa-lock"></i>
                <input asp-for="createacc.password" type="password" placeholder="Password">
            </div>
            <div class="forgot">
                <a href="#">Forgot Password ?</a>
            </div>
            <div class="login">
                <button asp-page-handler="Create" type="submit">Create</button>
            </div>
            <div class="signup">
                Have an account ? <a href="/Index">Login</a>
            </div>
        </form>
    </div>

</body>
</html>

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/CreatePlayer.cshtml
@page
@model SongcayawoninalIPT102ProjectFinal.Pages.CreatePlayerModel
@{
}
<form method="post">
    <h1 class="title text-center mb-4">Get Contact</h1>

    <div class="form-group position-relative">
        <label for="formFirstName">
            <i class="icon" data-feather="user"></i>
        </label>
        <input asp-for="playerInput.PlayerName" type="text" id="formFirstName" class="form-control form-control-lg thick" placeholder="PlayerName">
    </div>

    <div class="form-group position-relative">
        <label for="formLastName">
            <i class="icon" data-feather="mail"></i>
        </label>
        <input asp-for="playerInput.PlayerRank" type="text" id="formLastName" class="form-control form-control-lg thick" placeholder="LastName">
    </div>

    <div class="form-group position-relative">
        <label for="formEmail">
            <i class="icon" data-feather="mail"></i>
        </label>
        <input asp-for="playerInput.PlayerClass" type="email" id="formEmail" class="form-control form-control-lg thick" placeholder="E-mail">
    </div>

    <div class="text-center">
        <button asp-page-handler="Create" type="submit" class="btn btn-primary" tabIndex="-1">Save</button>
    </div>
</form>

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/Index.cshtml
@page
@model IndexModel
@{
    Layout = "LoginLayout";
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/Login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Responsive Login Form - Coding Power</title>
</head>
<body>

    <div class="container">
        <div class="title">
            <h2>Login</h2>
        </div>
        <form method="post">
            <div class="field">
                <i class="fa fa-envelope"></i>
                <input asp-for="acc.username" type="email" placeholder="Email">
            </div>
            <div class="field">
                <i class="fa fa-lock"></i>
                <input asp-for="acc.password" type="password" placeholder="Password">
            </div>
            <div class="forgot">
                <a href="#">Forgot Password ?</a>
            </div>
            <div class="login">
                <button asp-page-handler="Login" type="submit">Login</button>
            </div>
            <div class="signup">
                Don't have an account ? <a href="/Create">Signup Here</a>
            </div>
        </form>
    </div>

</body>
</html>

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/PlayerDetails.cshtml
@page
@model SongcayawoninalIPT102ProjectFinal.Pages.PlayerDetailsModel
@{
}

<h3>PlayerDetails</h3>

<h1 class="title text-center mb-4">Player Details</h1>

@if (Model.playerOptions != null)
{
    <form method="post">
        <select asp-for="PlayerDetailsId" class="select-option">
            @foreach (var option in Model.playerOptions)
            {
                <option value="@option?.PlayerId">@option?.PlayerName</option>
            }
        </select>
        <button asp-page-handler="PlayerDetailsDisplay" class="btn btn-primary">Check</button>
    </form>
}

<div class="form-group position-relative">
    <label>
        Name
    </label>
    <input asp-for="playD.PlayerName" type="text" class="form-control form-control-lg thick" readonly />
</div>

<div class="form-group position-relative">
    <label>
        Rank
    </label>
    <input asp-for="playD.PlayerRank" type="text" class="form-control form-control-lg thick" readonly />
</div>

<div class="form-group position-relative">
    <label>
        Class
    </label>
    <input asp-for="playD.PlayerClass" type="text" class="form-control form-control-lg thick" readonly />
</div>

<div class="text-center">
    <form method="post" asp-page-handler="PlayerDetailsDelete" asp-route-ID="@Model.playD.PlayerId">
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/PlayerDetailsUpdate.cshtml
@page
@model SongcayawoninalIPT102ProjectFinal.Pages.PlayerDetailsUpdateModel
@{
}
<h1 class="title text-center mb-4">Update Contact</h1>

@if (Model.playerOptions != null)
{
    <form method="post">
        <select class="select-option" asp-for="PlayerDetailsId">
            @foreach (var option in Model.playerOptions)
            {
                <option value="@option?.PlayerId">@option?.PlayerName   </option>
            }
        </select>
        <button asp-page-handler="PlayerDetailsDisplay" class="btn btn-primary">Check</button>
    </form>
}

<form method="post">

    <input asp-for="playUpdate.PlayerId" hidden/>
    <div class="form-group position-relative">
        <label>
           Player Name
        </label>
        <input type="text" class="form-control form-control-lg thick" asp-for="playUpdate.PlayerName">
    </div>

    <div class="form-group position-relative">
        <label>
            Player Rank
        </label>
        <input type="text" class="form-control form-control-lg thick" asp-for="playUpdate.PlayerRank">
    </div>

    <div class="form-group position-relative">
        <label>
           Player Class
        </label>
        <input type="text" class="form-control form-control-lg thick" asp-for="playUpdate.PlayerClass">
    </div>

    <div class="text-center">
        <button asp-page-handler="PlayerDetailsUpdate" class="btn btn-primary" tabIndex="-1">Update</button>
    </div>
</form>

SongcayawoninalIPT102ProjectFinal/SongcayawoninalIPT102ProjectFinal/Pages/SearchPlayer.cshtml
@page
@model SongcayawoninalIPT102ProjectFinal.Pages.SearchPlayerModel
@{
}
<form method="post">
    <input asp-for="plays.PlayerName" /> <button asp-page-handler="Search">Search</button>
</form>
</div>
<div class="table-container">
    <h2>Player List</h2>
    @if (Model.AllLogs != null && Model.AllLogs.Any())
    {
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Rank</th>
                    <th>Class</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var logEntry in Model.AllLogs)
                {
                    <tr>
                        <td>@logEntry.PlayerId</td>
                        <td>@logEntry.PlayerName</td>
                        <td>@logEntry.PlayerRank</td>
                        <td>@logEntry.PlayerClass</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No players found.</p>
    }
</div>